name: auth_client
description: Defines the abstract interface for authentication operations within the Headlines Toolkit, supporting email+code and anonymous flows.
repository: https://github.com/flutter-news-app-full-source-code/auth-client
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^9.0.0
